### ISSUE TITLE
wildcards not correctly matched in 0.6

### ISSUE THREAD

**Issue by ederag** [snoack/flake8-per-file-ignores#8]
in https://github.com/ederag/geoptics/blob/master/setup.cfg
`    tests/*: D100, D101, D102, D103` is not honored since 0.6.
`    tests/*.py: D100, D101, D102, D103` did not work either.

(it worked perfectly in 0.5, which was great, thanks for this tool!)

**Comment by snoack** [comment]
Can you please show the output you see?

**Comment by snoack** [comment]
Is it possible that you expect `*` to match across directory boundaries? That was a bug in older versions. Now you have to use `**` if you want to match recursively.

**Comment by ederag** [comment]
Exactly. Thanks for the quick answer !
Solved by https://github.com/ederag/geoptics/commit/4acca96ffaba93aff634183a47b3171b480d3c75

The [link](https://en.wikipedia.org/wiki/Glob_(programming)) given in the README.md is not accurate.
It should be replaced by https://github.com/demurgos/py-pathmatch
and perhaps give the same example ?
```
# Pattern matching auto-generated test files (extension .pyc, .pyo or .pyd inside tests/)
per-file-ignores == 'tests/**/*.py[cod]'
```

**Comment by snoack** [comment]
In standard UNIX glob patterns, `*` doesn't match across directory boundaries. You are right that `**` is a non-standard feature too (a side effect of - but not specific to - using the `pathmatch` module).

So now we could either accept that `**` is an undocumented feature (matter to change), just like the old (undocumented) semantics of `*`, or we could standardize something (i.e. put it in the README and tests).

**Comment by ederag** [comment]
@snoack 
> `*` in standard UNIX glob patterns doesn't match across directory boundaries

Not sure I get it. The `tests/*` did match `tests/gui/qt/conftest.py` for instance.

To be clear, the code is good, it does solve some use cases, 
and the new `**/` syntax is backward compatible (checked with 0.3..0.6).
So to me yes, it is merely a matter of documentation, and testing.
Besides, now that this issue can be found, transition should be easy, hopefully.

**Comment by snoack** [comment]
`*` is not supposed to match the path seperator (e.g. `/`), it doesn't if you use the `glob` module from the corelib, it doesn't either in any POSIX-compatible shell (e.g. Bash). This was a bug.

`**` is the defacto-standard syntax for recursive glob pattern path matches, the `glob` module (in newer Python versions) as well as Bash (and other shells) support it too (though not by default).

The reason `**` is backwards-compatible with (the broken behavior in) `flake8-per-file-ignores` <= 0.5 is because `**` in 0.6 has the same semantics as `*` (or a sequence of any number of subsequent `*` characters) had in older versions.

You have a point though, the Wikipedia article linked is indeed misleading, as it doesn't accurately outline the semantics of glob patterns in the context of (POSIX-compliant) path matching.
